---
title: "Dataset Explanation"
author: "Lewis Zou"
date: "11/27/2019"
output: html_fragment
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(tidyverse)
library(gt)

worlds_18 <- readRDS("clean-data/worlds_2018.rds")
```

```{r making the definition table}

def_table <- tribble(
~select, ~week, ~game, ~patchno, ~playerid, ~side, ~position, ~player, ~team, ~champion, ~ban, ~gamelength, ~result, ~k, ~d, ~a, ~teamkills, ~teamdeaths, ~doubles, ~triples, ~quadras, ~pentas, ~fb, ~fbassist, ~fbvictim, ~fbtime, ~kpm, ~okpm, ~ckpm, ~fd, ~fdtime, ~teamdragkills, ~oppdragkills, ~elementals, ~oppelementals, ~firedrakes, ~waterdrakes, ~earthdrakes, ~airdrakes, ~elders, ~oppelders, ~herald , ~hearldtime, ~ft, ~fttime, ~firstmidouter, ~firsttothreetowers, ~teamtowerkills, ~opptowerkills, ~fbaron, ~fbarontime, ~teambaronkills, ~oppbaronkills, ~dmgtochamps, ~dmgtochampsperminute, ~dmgshare, ~earnedgoldshare, ~wards, ~wpm, ~wardshare, ~wardkills, ~wcpm, ~visionwards, ~visionwardbuys, ~visiblewarclearrate, ~invisiblewardclearrate, ~totalgold, ~earnedgpm, ~goldspent, ~gspd, ~minionkills, ~monsterkills, ~monsterkillsownjungle, ~monsterkillsenemyjungle, ~cspm, ~goldat10, ~oppgoldat10, ~goldat15, ~oppgoldat15, ~gdat15, ~xpat15, ~oppxpat10, ~xpat10, ~csat10, ~oppcsat10, ~csdat10, ~xpdat10,
 "Select to get the definition",
 "Week game was played",
 "Game number for team",
 "Patch number (refers to the meta / style of gameplay)",
 "Player IDs",
 "Red or blue side of the game",
 "Position played",
 "Player name",
 "Team name",
 "Champion played",
 "Champion banned from playing (5 for each team)",
 "Length of game in minutes",
 "Win or loss (1 = win)",
 "Kills in game",
 "Deaths in game",
 "Assists in game",
 "Total team kills",
 "Total team deaths",
 "Double kills (2 kills within 10 seconds of each other)",
 "Triple kills (3 kills within 10 seconds of each other)",
 "Quadra kills (4 kills within 10 seconds of each other)",
 "Penta kills (5 kills within 10 seconds of each other)",
 "First blood (first kill in game)",
 "First blood assist (assist on first blood)",
 "First death (first death in game)",
 "Time of first blood",
 "Kills per minute",
 "Opponent kills per minute",
 "Champion kills per minute",
 "First team to have death",
 "TIme of first death",
 "Team dragon kills (elementals + elders)",
 "Opponent dragon kills",
 "Elemental dragon kills",
 "Opponent elemental dragon kills",
 "Fire dragon kills",
 "Water dragon kills",
 "Earth dragon kills",
 "Air dragon kills",
 "Elder dragon kills",
 "Opponent elder dragon kills",
 "Rift heralds",
 "Time of rift herald",
 "First tower",
 "Time of first tower",
 "First mid-lane outer tower",
 "First team to kill 3 towers",
 "Team tower kills",
 "Opponent tower kills",
 "First baron",
 "Time of first baron",
 "Team baron kills",
 "Opponent baron kills",
 "Damage to champions",
 "Damage to champions per minute",
 "Damage — percentage of team",
 "Gold earned — percentage of team",
 "Wards placed",
 "Wards placed per minute",
 "Wards placed — percentage of team",
 "Wards killed",
 "Wards clearned per minute",
 "Vision wards placed",
 "Vision wards bought",
 "Percentage of visible wards cleared",
 "Percentage of invisible wards cleared",
 "Total gold earned",
 "Gold earned per minute",
 "Gold spent",
 "Average gold spent percentage difference",
 "Minions killed",
 "Monsters killed",
 "Monsters killed in jungle on own side of map",
 "Monsters killed in jungle on enemy side of map",
 "CS (minions killed) per minute",
 "Gold earned at 10 minutes into the game",
 "Opponent gold earned at 15 minutes into the game",
 "Gold earned at 15 minutes into the game",
 "Opponent gold earned at 15 minutes into the game",
 "Gold difference at 15 minutes into the game",
 "Experience earned at 15 minutes into the game",
 "Opponent experience earned at 10 minutes into the game",
 "Experience earned at 10 minutes into the game",
 "CS (minions killed) at 10 minutes into the game",
 "Opponent CS (minions killed) at 10 minutes into the game",
 "Difference in CS (minions killed) at 10 minutes into the game",
 "Difference in experience at 10 minutes into the game",
)

saveRDS(def_table, "clean-data/definitions.rds")
```

